generic-y += cache.h
generic-y += extable.h
generic-y += irqflags.h
generic-y += local64.h
generic-y += mcs_spinlock.h
generic-y += qrwlock.h
generic-y += qspinlock.h
generic-y += user.h

include $(srctree)/arch/ish/$(ABI_ARCH)/include/asm/Kbuild
generated-y += $(redir-abi-y) $(redir-arch-y)
